name: ml4hc_project2_doc2vec
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - numpy==1.20.3
  - pandas=1.4.1
  - scikit-learn=0.24.2
  - pytorch=1.9.0
  - scipy=1.7.1
  - flake8=4.0.1
  - spacy=3.2.4
  - spacy-model-en_core_web_sm=3.2.0
  - jinja2=3.1.1
  - gensim=4.0.1
  - pip=22.0.4
  - pip:
    - ray==1.10.0
    - tensorflow==2.8.0
    - keras==2.8.0
    - tensorflow-addons==0.16.1